"""Add ondelete cascade to cart_item

Revision ID: 6475f871147c
Revises: a992722002fd
Create Date: 2025-01-16 11:10:52.325918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6475f871147c'
down_revision: Union[str, None] = 'a992722002fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_item_cart_id_fkey', 'cart_item', type_='foreignkey')
    op.create_foreign_key(None, 'cart_item', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.create_foreign_key('cart_item_cart_id_fkey', 'cart_item', 'cart', ['cart_id'], ['id'])
    # ### end Alembic commands ###
