"""Add ON DELETE CASCADE to cart_item_product_id_fkey

Revision ID: 816c50ccd635
Revises: 6475f871147c
Create Date: 2025-01-16 11:31:33.458168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816c50ccd635'
down_revision: Union[str, None] = '6475f871147c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_item_product_id_fkey', 'cart_item', type_='foreignkey')
    op.create_foreign_key(None, 'cart_item', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.create_foreign_key('cart_item_product_id_fkey', 'cart_item', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
